version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
  frontend:
    build:
      context: ./www
      dockerfile: Dockerfile
    depends_on:
      - "api"
    ports:
      - "80:80"