version: "3"
services:
  api:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/goecho-api:$CIRCLE_SHA1
    # image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/goecho-api:latest
    ports:
      - "8001:8001"
    logging:
      driver: awslogs
      options:
        awslogs-group: goping-api
        awslogs-region: $AWS_DEFAULT_REGION
        awslogs-stream-prefix: api
  frontend:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/goping-www:$CIRCLE_SHA1
    depends_on:
      - "api"
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: goping-api
        awslogs-region: $AWS_DEFAULT_REGION
        awslogs-stream-prefix: www  