version: "3"
services:
  api:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/goecho-api:$CIRCLE_SHA1
    ports:
      - "8001:8001"
    logging:
      driver: awslogs
      options:
        awslogs-group: goping-test
        awslogs-region: $AWS_DEFAULT_REGION
        awslogs-stream-prefix: api

# environmentを使う