version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.1
  aws-ecs: circleci/aws-ecs@1.1.0

jobs:
  deployment:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: ecs-cli install and configure
          command: |
            sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli
            ecs-cli --version
            ecs-cli configure --cluster goping-cluster --default-launch-type FARGATE --region $AWS_REGION --config-name goping-config
      - run:
          name: update
          command: |
            ecs-cli compose \
              --file docker-compose.ecs.yml \
              --ecs-params ecs-params.yml \
              --project-name goping-test \
              --cluster-config goping-config \
              service up \
              --load-balancer-name goping-lb \
              --container-name goping-test
              --container-port 8001

workflows:
  build-and-deploy:
    # Run the welcome/run job in its own container
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          path: './api' # Dockerfile
          repo: 'goecho-api'
          tag: '${CIRCLE_SHA1}'
      
      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - aws-ecr/build-and-push-image
      #     family: '${MY_APP_PREFIX}-service'
      #     cluster-name: '${MY_APP_PREFIX}-cluster'
      #     container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'

      - deployment:
          requires:
            - aws-ecr/build-and-push-image
